### PR TITLE
Got rid of PBR. It does not work with virtualenv

### PR DESCRIPTION
**Pull request by myoung34**
This python plugin is the only one that I can find that works with folders, and it's great.

However, I have had no luck getting it to install from any docker container that uses virtualenv, such as [errbot](https://github.com/errbotio/errbot)

My `requirements.txt`: 

```cat plugins/CI/requirements.txt
python-jenkins``` 

my full plugin code `ci.py`:

```
from errbot import BotPlugin, botcmd, arg_botcmd, webhook

import jenkins

JENKINS_CONN_STR = os.environ['STRATABOT_JENKINS_URL']
JENKINS_USERNAME = os.environ['STRATABOT_JENKINS_USERNAME']
JENKINS_PASSWORD = os.environ['STRATABOT_JENKINS_PASSWORD']

def connect_to_jenkins():
    server = jenkins.Jenkins(JENKINS_CONN_STR, username=JENKINS_USERNAME, password=JENKINS_PASSWORD)
    try:
        server.get_whoami()
    except jenkins.JenkinsException:
        raise Exception('Unable to connect to Jenkins')
    return server

class CiBot(BotPlugin):

    @botcmd(split_args_with=None)
    @arg_botcmd('--jobname', dest='job_name', type=str)
    def ci_test(self, message, job_name=None):
        server = connect_to_jenkins()
        jenkins_job_name = server.get_job_name(job_name)
        if not jenkins_job_name:
            yield "Did not find a job that matched '%s'" % job_name
        else:
            yield "Found job '%s'" % job_name
```

My `docker-compose.yml`:

```
cat docker-compose.yml
bot:
  container_name: err
  image: rroemhild/errbot
  environment:
    - STRATABOT_JENKINS_URL=http://odin:8080 #version 2.7.4
    - STRATABOT_JENKINS_PASSWORD=${STRATABOT_JENKINS_PASSWORD}
    - STRATABOT_JENKINS_USERNAME=${STRATABOT_JENKINS_USERNAME}
    - BACKEND=Text
    - ERRCONF=/srv/docker/config.py
  volumes:
    - .:/srv
  command: [ '/app/venv/bin/run.sh', '-c', '/srv/docker/config.py', '-T' ]
```

This results in:

```
Collecting python-jenkins (from -r ./plugins/CI/requirements.txt (line 1))
  Downloading python-jenkins-0.4.13.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 640kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 156, in save_modules
        yield saved
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 197, in setup_context
        yield
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 246, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 276, in run
        return func()
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 245, in runner
        _execfile(setup_script, ns)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-xvdd651o/pbr-1.10.0/setup.py", line 22, in <module>
      File "/tmp/easy_install-xvdd651o/pbr-1.10.0/pbr/util.py", line 264, in cfg_to_args
      File "/tmp/easy_install-xvdd651o/pbr-1.10.0/pbr/util.py", line 566, in wrap_commands
      File "/app/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2264, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named 'release'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cgtvip9o/python-jenkins/setup.py", line 5, in <module>
        pbr=True)
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/app/venv/lib/python3.4/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/app/venv/lib/python3.4/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/app/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 851, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/app/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1123, in best_match
        return self.obtain(req, installer)
      File "/app/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1135, in obtain
        return installer(requirement)
      File "/app/venv/lib/python3.4/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/app/venv/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/app/venv/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/app/venv/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/app/venv/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/app/venv/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
        run_setup(setup_script, args)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 249, in run_setup
        raise
      File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 197, in setup_context
        yield
      File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 168, in save_modules
        saved_exc.resume()
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 143, in resume
        six.reraise(type, exc, self._tb)
      File "/app/venv/lib/python3.4/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 156, in save_modules
        yield saved
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 197, in setup_context
        yield
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 246, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 276, in run
        return func()
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 245, in runner
        _execfile(setup_script, ns)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-xvdd651o/pbr-1.10.0/setup.py", line 22, in <module>
      File "/tmp/easy_install-xvdd651o/pbr-1.10.0/pbr/util.py", line 264, in cfg_to_args
      File "/tmp/easy_install-xvdd651o/pbr-1.10.0/pbr/util.py", line 566, in wrap_commands
      File "/app/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2264, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named 'release'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cgtvip9o/python-jenkins/
14:29:26 ERROR    errbot.plugin_manager     Failed to execute pip install for ./plugins/CI/requirements.txt.
Traceback (most recent call last):
  File "/app/venv/lib/python3.4/site-packages/errbot/plugin_manager.py", line 61, in install_packages
    subprocess.check_call(['pip', 'install', '--requirement', req_path])
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'install', '--requirement', './plugins/CI/requirements.txt']' returned non-zero exit status 1
14:29:26 ERROR    yapsy                     Unable to import plugin: /srv/plugins/CI/ci
```

### CODE REVIEW

**Comment by myoung34** [comment]
This also happens exactly the same on a non-docker instance running `virtualenv`.
Not sure if the problem is exactly virtualenv, but im unable to get this to build when `PBR` is involved.

Using the code from this PR results in success.
Same `docker-compose.yml`, with `requirements.txt` modified to:

```
$ cat plugins/CI/requirements.txt
git+git://github.com/myoung34/python-jenkins
```

results in:

```
14:33:22 INFO     errbot.plugin_manager     Installing packages from './plugins/CI/requirements.txt'.
Collecting git+git://github.com/stratasan/python-jenkins (from -r ./plugins/CI/requirements.txt (line 1))
  Cloning git://github.com/stratasan/python-jenkins to /tmp/pip-m7dbgqzp-build
Requirement already satisfied (use --upgrade to upgrade): six>=1.3.0 in /app/venv/lib/python3.4/site-packages (from jenkins==0.4.13->-r ./plugins/CI/requirements.txt (line 1))
Collecting multi_key_dict (from jenkins==0.4.13->-r ./plugins/CI/requirements.txt (line 1))
  Downloading multi_key_dict-2.0.3.tar.gz
Building wheels for collected packages: multi-key-dict
  Running setup.py bdist_wheel for multi-key-dict ... done
  Stored in directory: /srv/.cache/pip/wheels/7a/58/46/ded159f81ab3f2fce93eca7eea0b6d7db12375690acd8040f2
Successfully built multi-key-dict
Installing collected packages: multi-key-dict, jenkins
  Running setup.py install for jenkins ... done
Successfully installed jenkins-0.4.13 multi-key-dict-2.0.3
```

**Comment by openstack-gerrit** [comment]
Thank you for contributing to openstack/python-jenkins!

openstack/python-jenkins uses Gerrit for code review.

If you have never contributed to OpenStack before make sure you have read the
getting started documentation:
http://docs.openstack.org/infra/manual/developers.html#getting-started

Otherwise please visit
http://docs.openstack.org/infra/manual/developers.html#development-workflow
and follow the instructions there to upload your change to Gerrit.

**Comment by cboylan** [comment]
I believe this is a symptom of using really old pip and setuptools inside of virtualenv. You should upgrade your version of virtualenv (which bundles pip and setuptools) to correct this.

**Comment by myoung34** [comment]
@cboylan I'm still not able to use the upstream version of this.

The dockerfile: https://github.com/rroemhild/docker-errbot/blob/master/Dockerfile

```
err@fc1d967c3f6b:~$ dpkg -l | grep setup
ii  dmsetup                    2:1.02.90-2.2+deb8u1      amd64        Linux Kernel Device Mapper userspace library
ii  libcryptsetup4:amd64       2:1.6.6-5                 amd64        disk encryption support - shared library
ii  python3-setuptools         5.5.1-1                   all          Python3 Distutils Enhancements
err@fc1d967c3f6b:~$ pip list | grep setuptools
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
setuptools (34.1.1)
err@fc1d967c3f6b:~$ pip --version
pip 9.0.1 from /app/venv/lib/python3.4/site-packages (python 3.4)
err@fc1d967c3f6b:~$ pip install --requirement ./plugins/Bot/requirements.txt
Collecting boto3 (from -r ./plugins/Bot/requirements.txt (line 1))
  Using cached boto3-1.4.4-py2.py3-none-any.whl
Collecting python-jenkins (from -r ./plugins/Bot/requirements.txt (line 2))
  Using cached python-jenkins-0.4.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 255, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 285, in run
        return func()
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 253, in runner
        _execfile(setup_script, ns)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-8q6_hov_/pbr-1.10.0/setup.py", line 22, in <module>
      File "/tmp/easy_install-8q6_hov_/pbr-1.10.0/pbr/util.py", line 264, in cfg_to_args
      File "/tmp/easy_install-8q6_hov_/pbr-1.10.0/pbr/util.py", line 566, in wrap_commands
      File "/app/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2302, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named 'release'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-st_j1_4w/python-jenkins/setup.py", line 5, in <module>
        pbr=True)
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/app/venv/lib/python3.4/site-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/app/venv/lib/python3.4/site-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/app/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 851, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/app/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1123, in best_match
        return self.obtain(req, installer)
      File "/app/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1135, in obtain
        return installer(requirement)
      File "/app/venv/lib/python3.4/site-packages/setuptools/dist.py", line 440, in fetch_build_egg
        return cmd.easy_install(req)
      File "/app/venv/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/app/venv/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 700, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/app/venv/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/app/venv/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/app/venv/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
        run_setup(setup_script, args)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 258, in run_setup
        raise
      File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "/app/venv/lib/python3.4/site-packages/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 255, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 285, in run
        return func()
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 253, in runner
        _execfile(setup_script, ns)
      File "/app/venv/lib/python3.4/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-8q6_hov_/pbr-1.10.0/setup.py", line 22, in <module>
      File "/tmp/easy_install-8q6_hov_/pbr-1.10.0/pbr/util.py", line 264, in cfg_to_args
      File "/tmp/easy_install-8q6_hov_/pbr-1.10.0/pbr/util.py", line 566, in wrap_commands
      File "/app/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2302, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named 'release'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-st_j1_4w/python-jenkins/
```

**Comment by cboylan** [comment]
If I do similar (big difference is python3.5 vs 3.4) it seems to work fine. Maybe related to that?

```
clark@nibbler:~/tmp$ virtualenv-3.5 venv35
Using base prefix '/usr'
New python executable in /home/clark/tmp/venv35/bin/python3
Also creating executable in /home/clark/tmp/venv35/bin/python
Installing setuptools, pip, wheel...done.
clark@nibbler:~/tmp$ source venv35/bin/activate
(venv35) clark@nibbler:~/tmp$ pip list | grep setuptools
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
setuptools (34.1.1)
(venv35) clark@nibbler:~/tmp$ pip --version
pip 9.0.1 from /home/clark/tmp/venv35/lib/python3.5/site-packages (python 3.5)
(venv35) clark@nibbler:~/tmp$ pip install python-jenkins
Collecting python-jenkins
Collecting pbr<2.0,>=0.8.2 (from python-jenkins)
  Using cached pbr-1.10.0-py2.py3-none-any.whl
Collecting multi-key-dict (from python-jenkins)
Requirement already satisfied: six>=1.3.0 in ./venv35/lib/python3.5/site-packages (from python-jenkins)
Installing collected packages: pbr, multi-key-dict, python-jenkins
Successfully installed multi-key-dict-2.0.3 pbr-1.10.0 python-jenkins-0.4.13
(venv35) clark@nibbler:~/tmp$ 
```

**Pull request closed without merging**
